---
pygments: true
markdown: kramdown
include: _index.html
defaultnav: 
  /: quick_nav.html
  /mcollective: mcollective_menu.html
  /pe/2.7: pe27.html
  /pe/2.6: pe26.html
  /pe/2.5: pe25.html
  /pe/2.0: pe_2.0_nav.markdown
  /puppetdb/0.9: puppetdb0.9.html
  /puppetdb/1: puppetdb1.html
  /puppetdb/1.1: puppetdb1.1.html
  /puppet/0.24/reference: puppet_0_24.html
  /puppet/0.25/reference: puppet_0_25.html
  /puppet/2.6/reference: puppet_2_6.html
  /puppet/2.7/reference: puppet_2_7.html
  /puppet/3/reference: puppet_reference_3.html
  /references: references_general.html
  /hiera/1: hiera1.html
  /guides/deployment_guide:  deploy_guide.html
  /puppet/release_notes: puppet_release_notes.html
destination: ../output
url: "http://docs.puppetlabs.com"
externalsources:
  puppetdb_1.1:
    url: /puppetdb/1.1
    repo: git://github.com/puppetlabs/puppetdb.git
    # Change this to origin/1.1.x once puppetdb team cuts a branch
    commit: origin/1.1.x
    subdirectory: documentation
  puppetdb_master:
    url: /puppetdb/master
    repo: git://github.com/puppetlabs/puppetdb.git
    commit: origin/master
    subdirectory: documentation
  marionette-collective:
    url: /mcollective
    repo: git://github.com/puppetlabs/marionette-collective.git
    commit: origin/master
    subdirectory: website
symlink_latest:
  - puppet
  - puppetdb
  - hiera
  - facter
  - pe
  - dashboard/manual
---
